on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

  push:
    branches:
    - main
    - master
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "**/.editorconfig"
      - "**/*.runsettings"
      - "**/typos.toml"
      - ".github/**"
      - "!.github/workflows/semgrep.yml"
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      reason:
        description: "The reason for running the workflow"
        required: true
        default: "Manual run"
name: Semgrep
jobs:
  semgrep:
    name: Semgrep/CI
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4.2.2
    - name: "Check for changed files"
      uses: dorny/paths-filter@v3
      id: filter
      with:
        predicate-quantifier: 'every'
        filters: |
          code:
            - "!**/*.md"
            - "!**/*.txt"
            - "!**/.editorconfig"
            - "!**/*.runsettings"
            - "!**/typos.toml"
            - "!.github/**"
          workflow:
            - ".github/workflows/semgrep.yml"

    - name: 'Run Semgrep'
      if: steps.filter.outputs.code == 'true' || steps.filter.outputs.workflow == 'true'
      run: semgrep ci
