name: "Run tests"

on:
  push:
  pull_request:
    paths:
      - "**.cs"
      - "**.csproj"
permissions:
  contents: read

jobs:
  test:
    name: test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2.1.1
        with:
          dotnet-version: "6.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --no-restore --verbosity normal --logger GitHubActions

      - name: Code coverage
        uses:  codecov/codecov-action@v3.1.1
        with:
          flags: unittests
          verbose: true
